exports.activitylist = function(){  
   activities_list = [
        "goat simulator",
        "the BYAND",
        "planetary annihalation",
        "HE-MAN HEYEAYEA SONG FOR 10 HOURS",
        "OWO what's this???",
        "My Little Pony: Friendship is Magic",
        "the role of the secretary we never had",
        "Halo MCCPC",
        "Destiny",
        "KFC dating simulator",
        "Warcraft: Reforged",
        "Battletoads 2",
        "Nightmares of a forgotten past",
        "Nightcrawlers",
        "Lo-fi HipHop Beats to Study to",
        "the harpsichord",
        "nu-wave jazz-grunge",
        "alternative polka",
        "rollercoaster tycoon 3",
        "minecraft",
        "the stock market",
        "the slots in vegas",
        "Destroy All Humans",
        "Flying Microtonal Banana",
        "Eyes Like The Sky",
        "Nonagon Infinity",
        "Polygondwanaland",
        "Float Along Fill Your Lungs",
        "Quarters",
        "Infest the Rats Nest",
        "Fishing For Fishies",
        "Gumboot Soup",
        "12 Bar Bruise",
        "Sketches of Brunswick East",
        "Paper Mache Dream Balloon",
        "I'm In Your Mind Fuzz",
        "Murder of The Universe",
        "Oddments",
        "Willoughby's Beach"
        ]; // creates an arraylist containing phrases you want your bot to switch through.
        return activities_list
}